[
  {
    id: 245,
    description: "",
    name: "gui",
    name_with_namespace: "beaurld / gui",
    path: "gui",
    path_with_namespace: "beaurld/gui",
    created_at: "2022-01-16T02:58:00.869Z",
    default_branch: "master",
    tag_list: [],
    topics: [],
    ssh_url_to_repo: "git@gitlab.gerpgo.com:beaurld/gui.git",
    http_url_to_repo: "http://gitlab.gerpgo.com/beaurld/gui.git",
    web_url: "http://gitlab.gerpgo.com/beaurld/gui",
    readme_url: "http://gitlab.gerpgo.com/beaurld/gui/-/blob/master/README.md",
    avatar_url: null,
    forks_count: 0,
    star_count: 0,
    last_activity_at: "2023-01-11T08:18:02.563Z",
    namespace: {
      id: 196,
      name: "beaurld",
      path: "beaurld",
      kind: "group",
      full_path: "beaurld",
      parent_id: null,
      avatar_url: null,
      web_url: "http://gitlab.gerpgo.com/groups/beaurld",
    },
    _links: {
      self: "http://gitlab.gerpgo.com/api/v4/projects/245",
      issues: "http://gitlab.gerpgo.com/api/v4/projects/245/issues",
      merge_requests:
        "http://gitlab.gerpgo.com/api/v4/projects/245/merge_requests",
      repo_branches:
        "http://gitlab.gerpgo.com/api/v4/projects/245/repository/branches",
      labels: "http://gitlab.gerpgo.com/api/v4/projects/245/labels",
      events: "http://gitlab.gerpgo.com/api/v4/projects/245/events",
      members: "http://gitlab.gerpgo.com/api/v4/projects/245/members",
    },
    packages_enabled: true,
    empty_repo: false,
    archived: false,
    visibility: "private",
    resolve_outdated_diff_discussions: false,
    container_expiration_policy: {
      cadence: "1d",
      enabled: false,
      keep_n: 10,
      older_than: "90d",
      name_regex: ".*",
      name_regex_keep: null,
      next_run_at: "2022-01-17T02:58:00.926Z",
    },
    issues_enabled: true,
    merge_requests_enabled: true,
    wiki_enabled: true,
    jobs_enabled: true,
    snippets_enabled: true,
    container_registry_enabled: true,
    service_desk_enabled: false,
    service_desk_address: null,
    can_create_merge_request_in: true,
    issues_access_level: "enabled",
    repository_access_level: "enabled",
    merge_requests_access_level: "enabled",
    forking_access_level: "enabled",
    wiki_access_level: "enabled",
    builds_access_level: "enabled",
    snippets_access_level: "enabled",
    pages_access_level: "private",
    operations_access_level: "enabled",
    analytics_access_level: "enabled",
    container_registry_access_level: "enabled",
    emails_disabled: null,
    shared_runners_enabled: true,
    lfs_enabled: true,
    creator_id: 9,
    import_status: "none",
    open_issues_count: 0,
    ci_default_git_depth: 50,
    ci_forward_deployment_enabled: true,
    ci_job_token_scope_enabled: false,
    public_jobs: true,
    build_timeout: 3600,
    auto_cancel_pending_pipelines: "enabled",
    build_coverage_regex: null,
    ci_config_path: null,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: false,
    allow_merge_on_skipped_pipeline: null,
    restrict_user_defined_variables: false,
    request_access_enabled: true,
    only_allow_merge_if_all_discussions_are_resolved: false,
    remove_source_branch_after_merge: true,
    printing_merge_request_link_enabled: true,
    merge_method: "merge",
    squash_option: "default_off",
    suggestion_commit_message: null,
    auto_devops_enabled: false,
    auto_devops_deploy_strategy: "continuous",
    autoclose_referenced_issues: true,
    keep_latest_artifact: true,
    permissions: { project_access: [Object], group_access: null },
  },
  {
    id: 233,
    description: "",
    name: "webhooks",
    name_with_namespace: "艾双杰 / webhooks",
    path: "webhooks",
    path_with_namespace: "aishuangjie/webhooks",
    created_at: "2022-01-08T03:21:21.511Z",
    default_branch: "main",
    tag_list: [],
    topics: [],
    ssh_url_to_repo: "git@gitlab.gerpgo.com:aishuangjie/webhooks.git",
    http_url_to_repo: "http://gitlab.gerpgo.com/aishuangjie/webhooks.git",
    web_url: "http://gitlab.gerpgo.com/aishuangjie/webhooks",
    readme_url:
      "http://gitlab.gerpgo.com/aishuangjie/webhooks/-/blob/main/README.md",
    avatar_url: null,
    forks_count: 0,
    star_count: 0,
    last_activity_at: "2022-01-08T03:21:21.511Z",
    namespace: {
      id: 212,
      name: "艾双杰",
      path: "aishuangjie",
      kind: "user",
      full_path: "aishuangjie",
      parent_id: null,
      avatar_url:
        "https://www.gravatar.com/avatar/8b4ad1442b32ba5f9b8bb0b395035f1f?s=80&d=identicon",
      web_url: "http://gitlab.gerpgo.com/aishuangjie",
    },
    _links: {
      self: "http://gitlab.gerpgo.com/api/v4/projects/233",
      issues: "http://gitlab.gerpgo.com/api/v4/projects/233/issues",
      merge_requests:
        "http://gitlab.gerpgo.com/api/v4/projects/233/merge_requests",
      repo_branches:
        "http://gitlab.gerpgo.com/api/v4/projects/233/repository/branches",
      labels: "http://gitlab.gerpgo.com/api/v4/projects/233/labels",
      events: "http://gitlab.gerpgo.com/api/v4/projects/233/events",
      members: "http://gitlab.gerpgo.com/api/v4/projects/233/members",
    },
    packages_enabled: true,
    empty_repo: false,
    archived: false,
    visibility: "public",
    owner: {
      id: 188,
      name: "艾双杰",
      username: "aishuangjie",
      state: "blocked",
      avatar_url:
        "https://www.gravatar.com/avatar/8b4ad1442b32ba5f9b8bb0b395035f1f?s=80&d=identicon",
      web_url: "http://gitlab.gerpgo.com/aishuangjie",
    },
    resolve_outdated_diff_discussions: false,
    container_expiration_policy: {
      cadence: "1d",
      enabled: false,
      keep_n: 10,
      older_than: "90d",
      name_regex: ".*",
      name_regex_keep: null,
      next_run_at: "2022-01-09T03:21:21.571Z",
    },
    issues_enabled: true,
    merge_requests_enabled: true,
    wiki_enabled: true,
    jobs_enabled: true,
    snippets_enabled: true,
    container_registry_enabled: true,
    service_desk_enabled: false,
    service_desk_address: null,
    can_create_merge_request_in: true,
    issues_access_level: "enabled",
    repository_access_level: "enabled",
    merge_requests_access_level: "enabled",
    forking_access_level: "enabled",
    wiki_access_level: "enabled",
    builds_access_level: "enabled",
    snippets_access_level: "enabled",
    pages_access_level: "enabled",
    operations_access_level: "enabled",
    analytics_access_level: "enabled",
    container_registry_access_level: "enabled",
    emails_disabled: null,
    shared_runners_enabled: true,
    lfs_enabled: true,
    creator_id: 188,
    import_status: "none",
    open_issues_count: 0,
    ci_default_git_depth: 50,
    ci_forward_deployment_enabled: true,
    ci_job_token_scope_enabled: false,
    public_jobs: true,
    build_timeout: 3600,
    auto_cancel_pending_pipelines: "enabled",
    build_coverage_regex: null,
    ci_config_path: null,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: false,
    allow_merge_on_skipped_pipeline: null,
    restrict_user_defined_variables: false,
    request_access_enabled: true,
    only_allow_merge_if_all_discussions_are_resolved: false,
    remove_source_branch_after_merge: true,
    printing_merge_request_link_enabled: true,
    merge_method: "merge",
    squash_option: "default_off",
    suggestion_commit_message: null,
    auto_devops_enabled: true,
    auto_devops_deploy_strategy: "continuous",
    autoclose_referenced_issues: true,
    keep_latest_artifact: true,
    permissions: { project_access: null, group_access: null },
  },
  {
    id: 210,
    description: "",
    name: "gerp-demo",
    name_with_namespace: "gerp-internal / gerp-demo",
    path: "gerp-demo",
    path_with_namespace: "gerp-internal/gerp-demo",
    created_at: "2021-12-21T03:20:46.734Z",
    default_branch: "master",
    tag_list: [],
    topics: [],
    ssh_url_to_repo: "git@gitlab.gerpgo.com:gerp-internal/gerp-demo.git",
    http_url_to_repo: "http://gitlab.gerpgo.com/gerp-internal/gerp-demo.git",
    web_url: "http://gitlab.gerpgo.com/gerp-internal/gerp-demo",
    readme_url: null,
    avatar_url: null,
    forks_count: 0,
    star_count: 0,
    last_activity_at: "2022-08-11T07:09:33.663Z",
    namespace: {
      id: 248,
      name: "gerp-internal",
      path: "gerp-internal",
      kind: "group",
      full_path: "gerp-internal",
      parent_id: null,
      avatar_url: null,
      web_url: "http://gitlab.gerpgo.com/groups/gerp-internal",
    },
    _links: {
      self: "http://gitlab.gerpgo.com/api/v4/projects/210",
      issues: "http://gitlab.gerpgo.com/api/v4/projects/210/issues",
      merge_requests:
        "http://gitlab.gerpgo.com/api/v4/projects/210/merge_requests",
      repo_branches:
        "http://gitlab.gerpgo.com/api/v4/projects/210/repository/branches",
      labels: "http://gitlab.gerpgo.com/api/v4/projects/210/labels",
      events: "http://gitlab.gerpgo.com/api/v4/projects/210/events",
      members: "http://gitlab.gerpgo.com/api/v4/projects/210/members",
    },
    packages_enabled: true,
    empty_repo: false,
    archived: false,
    visibility: "internal",
    resolve_outdated_diff_discussions: false,
    container_expiration_policy: {
      cadence: "1d",
      enabled: false,
      keep_n: 10,
      older_than: "90d",
      name_regex: null,
      name_regex_keep: null,
      next_run_at: "2021-12-28T06:50:14.363Z",
    },
    issues_enabled: true,
    merge_requests_enabled: true,
    wiki_enabled: true,
    jobs_enabled: true,
    snippets_enabled: true,
    container_registry_enabled: true,
    service_desk_enabled: false,
    service_desk_address: null,
    can_create_merge_request_in: true,
    issues_access_level: "enabled",
    repository_access_level: "enabled",
    merge_requests_access_level: "enabled",
    forking_access_level: "enabled",
    wiki_access_level: "enabled",
    builds_access_level: "enabled",
    snippets_access_level: "enabled",
    pages_access_level: "private",
    operations_access_level: "enabled",
    analytics_access_level: "enabled",
    container_registry_access_level: "enabled",
    emails_disabled: null,
    shared_runners_enabled: true,
    lfs_enabled: true,
    creator_id: 172,
    import_status: "none",
    open_issues_count: 0,
    ci_default_git_depth: 50,
    ci_forward_deployment_enabled: true,
    ci_job_token_scope_enabled: false,
    public_jobs: true,
    build_timeout: 3600,
    auto_cancel_pending_pipelines: "enabled",
    build_coverage_regex: null,
    ci_config_path: null,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: false,
    allow_merge_on_skipped_pipeline: null,
    restrict_user_defined_variables: false,
    request_access_enabled: true,
    only_allow_merge_if_all_discussions_are_resolved: false,
    remove_source_branch_after_merge: true,
    printing_merge_request_link_enabled: true,
    merge_method: "merge",
    squash_option: "default_off",
    suggestion_commit_message: null,
    auto_devops_enabled: false,
    auto_devops_deploy_strategy: "continuous",
    autoclose_referenced_issues: true,
    keep_latest_artifact: true,
    permissions: { project_access: null, group_access: null },
  },
  {
    id: 171,
    description: "",
    name: "retailerssdk",
    name_with_namespace: "retailerssdk / retailerssdk",
    path: "retailerssdk",
    path_with_namespace: "retailerssdk/retailerssdk",
    created_at: "2021-11-26T07:45:06.077Z",
    default_branch: "master",
    tag_list: [],
    topics: [],
    ssh_url_to_repo: "git@gitlab.gerpgo.com:retailerssdk/retailerssdk.git",
    http_url_to_repo: "http://gitlab.gerpgo.com/retailerssdk/retailerssdk.git",
    web_url: "http://gitlab.gerpgo.com/retailerssdk/retailerssdk",
    readme_url: null,
    avatar_url: null,
    forks_count: 0,
    star_count: 0,
    last_activity_at: "2021-11-29T03:16:14.173Z",
    namespace: {
      id: 231,
      name: "retailerssdk",
      path: "retailerssdk",
      kind: "group",
      full_path: "retailerssdk",
      parent_id: null,
      avatar_url: null,
      web_url: "http://gitlab.gerpgo.com/groups/retailerssdk",
    },
    _links: {
      self: "http://gitlab.gerpgo.com/api/v4/projects/171",
      issues: "http://gitlab.gerpgo.com/api/v4/projects/171/issues",
      merge_requests:
        "http://gitlab.gerpgo.com/api/v4/projects/171/merge_requests",
      repo_branches:
        "http://gitlab.gerpgo.com/api/v4/projects/171/repository/branches",
      labels: "http://gitlab.gerpgo.com/api/v4/projects/171/labels",
      events: "http://gitlab.gerpgo.com/api/v4/projects/171/events",
      members: "http://gitlab.gerpgo.com/api/v4/projects/171/members",
    },
    packages_enabled: true,
    empty_repo: false,
    archived: false,
    visibility: "internal",
    resolve_outdated_diff_discussions: false,
    container_expiration_policy: {
      cadence: "1d",
      enabled: false,
      keep_n: 10,
      older_than: "90d",
      name_regex: null,
      name_regex_keep: null,
      next_run_at: "2021-12-29T00:50:09.074Z",
    },
    issues_enabled: true,
    merge_requests_enabled: true,
    wiki_enabled: true,
    jobs_enabled: true,
    snippets_enabled: true,
    container_registry_enabled: true,
    service_desk_enabled: false,
    service_desk_address: null,
    can_create_merge_request_in: true,
    issues_access_level: "enabled",
    repository_access_level: "enabled",
    merge_requests_access_level: "enabled",
    forking_access_level: "enabled",
    wiki_access_level: "enabled",
    builds_access_level: "enabled",
    snippets_access_level: "enabled",
    pages_access_level: "private",
    operations_access_level: "enabled",
    analytics_access_level: "enabled",
    container_registry_access_level: "enabled",
    emails_disabled: null,
    shared_runners_enabled: true,
    lfs_enabled: true,
    creator_id: 185,
    import_status: "none",
    open_issues_count: 0,
    ci_default_git_depth: 50,
    ci_forward_deployment_enabled: true,
    ci_job_token_scope_enabled: false,
    public_jobs: true,
    build_timeout: 3600,
    auto_cancel_pending_pipelines: "enabled",
    build_coverage_regex: null,
    ci_config_path: null,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: false,
    allow_merge_on_skipped_pipeline: null,
    restrict_user_defined_variables: false,
    request_access_enabled: true,
    only_allow_merge_if_all_discussions_are_resolved: false,
    remove_source_branch_after_merge: true,
    printing_merge_request_link_enabled: true,
    merge_method: "merge",
    squash_option: "default_off",
    suggestion_commit_message: null,
    auto_devops_enabled: false,
    auto_devops_deploy_strategy: "continuous",
    autoclose_referenced_issues: true,
    keep_latest_artifact: true,
    permissions: { project_access: null, group_access: null },
  },
  {
    id: 145,
    description: "X版前端（VUE）",
    name: "erp-web-vue",
    name_with_namespace: "erp / erp-web-vue",
    path: "erp-web-vue",
    path_with_namespace: "erp/erp-web-vue",
    created_at: "2021-10-26T03:44:27.603Z",
    default_branch: "master",
    tag_list: [],
    topics: [],
    ssh_url_to_repo: "git@gitlab.gerpgo.com:erp/erp-web-vue.git",
    http_url_to_repo: "http://gitlab.gerpgo.com/erp/erp-web-vue.git",
    web_url: "http://gitlab.gerpgo.com/erp/erp-web-vue",
    readme_url:
      "http://gitlab.gerpgo.com/erp/erp-web-vue/-/blob/master/README.md",
    avatar_url: null,
    forks_count: 1,
    star_count: 1,
    last_activity_at: "2023-01-11T08:44:22.540Z",
    namespace: {
      id: 2,
      name: "erp",
      path: "erp",
      kind: "group",
      full_path: "erp",
      parent_id: null,
      avatar_url: null,
      web_url: "http://gitlab.gerpgo.com/groups/erp",
    },
    _links: {
      self: "http://gitlab.gerpgo.com/api/v4/projects/145",
      issues: "http://gitlab.gerpgo.com/api/v4/projects/145/issues",
      merge_requests:
        "http://gitlab.gerpgo.com/api/v4/projects/145/merge_requests",
      repo_branches:
        "http://gitlab.gerpgo.com/api/v4/projects/145/repository/branches",
      labels: "http://gitlab.gerpgo.com/api/v4/projects/145/labels",
      events: "http://gitlab.gerpgo.com/api/v4/projects/145/events",
      members: "http://gitlab.gerpgo.com/api/v4/projects/145/members",
    },
    packages_enabled: true,
    empty_repo: false,
    archived: false,
    visibility: "private",
    resolve_outdated_diff_discussions: false,
    container_expiration_policy: {
      cadence: "1d",
      enabled: false,
      keep_n: 10,
      older_than: "90d",
      name_regex: null,
      name_regex_keep: null,
      next_run_at: "2021-12-28T11:50:37.995Z",
    },
    issues_enabled: true,
    merge_requests_enabled: true,
    wiki_enabled: true,
    jobs_enabled: true,
    snippets_enabled: true,
    container_registry_enabled: true,
    service_desk_enabled: false,
    service_desk_address: null,
    can_create_merge_request_in: true,
    issues_access_level: "enabled",
    repository_access_level: "enabled",
    merge_requests_access_level: "enabled",
    forking_access_level: "enabled",
    wiki_access_level: "enabled",
    builds_access_level: "enabled",
    snippets_access_level: "enabled",
    pages_access_level: "private",
    operations_access_level: "enabled",
    analytics_access_level: "enabled",
    container_registry_access_level: "enabled",
    emails_disabled: null,
    shared_runners_enabled: true,
    lfs_enabled: true,
    creator_id: 6,
    import_status: "none",
    open_issues_count: 0,
    ci_default_git_depth: 50,
    ci_forward_deployment_enabled: true,
    ci_job_token_scope_enabled: false,
    public_jobs: true,
    build_timeout: 3600,
    auto_cancel_pending_pipelines: "enabled",
    build_coverage_regex: null,
    ci_config_path: null,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: false,
    allow_merge_on_skipped_pipeline: null,
    restrict_user_defined_variables: false,
    request_access_enabled: true,
    only_allow_merge_if_all_discussions_are_resolved: false,
    remove_source_branch_after_merge: true,
    printing_merge_request_link_enabled: true,
    merge_method: "merge",
    squash_option: "default_off",
    suggestion_commit_message: null,
    auto_devops_enabled: false,
    auto_devops_deploy_strategy: "continuous",
    autoclose_referenced_issues: true,
    keep_latest_artifact: true,
    permissions: { project_access: [Object], group_access: null },
  },
  {
    id: 76,
    description: "Archery二次开发",
    name: "Archery",
    name_with_namespace: "李园 / Archery",
    path: "archery",
    path_with_namespace: "liyuan/archery",
    created_at: "2021-07-13T10:17:23.363Z",
    default_branch: "master",
    tag_list: [],
    topics: [],
    ssh_url_to_repo: "git@gitlab.gerpgo.com:liyuan/archery.git",
    http_url_to_repo: "http://gitlab.gerpgo.com/liyuan/archery.git",
    web_url: "http://gitlab.gerpgo.com/liyuan/archery",
    readme_url:
      "http://gitlab.gerpgo.com/liyuan/archery/-/blob/master/README.md",
    avatar_url: null,
    forks_count: 0,
    star_count: 0,
    last_activity_at: "2021-08-27T09:03:01.424Z",
    namespace: {
      id: 134,
      name: "李园",
      path: "liyuan",
      kind: "user",
      full_path: "liyuan",
      parent_id: null,
      avatar_url:
        "https://www.gravatar.com/avatar/1017b2193c7f4c14985b1ce34d76c053?s=80&d=identicon",
      web_url: "http://gitlab.gerpgo.com/liyuan",
    },
    _links: {
      self: "http://gitlab.gerpgo.com/api/v4/projects/76",
      issues: "http://gitlab.gerpgo.com/api/v4/projects/76/issues",
      merge_requests:
        "http://gitlab.gerpgo.com/api/v4/projects/76/merge_requests",
      repo_branches:
        "http://gitlab.gerpgo.com/api/v4/projects/76/repository/branches",
      labels: "http://gitlab.gerpgo.com/api/v4/projects/76/labels",
      events: "http://gitlab.gerpgo.com/api/v4/projects/76/events",
      members: "http://gitlab.gerpgo.com/api/v4/projects/76/members",
    },
    packages_enabled: true,
    empty_repo: false,
    archived: false,
    visibility: "public",
    owner: {
      id: 123,
      name: "李园",
      username: "liyuan",
      state: "active",
      avatar_url:
        "https://www.gravatar.com/avatar/1017b2193c7f4c14985b1ce34d76c053?s=80&d=identicon",
      web_url: "http://gitlab.gerpgo.com/liyuan",
    },
    resolve_outdated_diff_discussions: false,
    container_expiration_policy: {
      cadence: "1d",
      enabled: false,
      keep_n: 10,
      older_than: "90d",
      name_regex: null,
      name_regex_keep: null,
      next_run_at: "2021-12-28T16:50:18.441Z",
    },
    issues_enabled: true,
    merge_requests_enabled: true,
    wiki_enabled: true,
    jobs_enabled: true,
    snippets_enabled: true,
    container_registry_enabled: true,
    service_desk_enabled: false,
    service_desk_address: null,
    can_create_merge_request_in: true,
    issues_access_level: "enabled",
    repository_access_level: "enabled",
    merge_requests_access_level: "enabled",
    forking_access_level: "enabled",
    wiki_access_level: "enabled",
    builds_access_level: "enabled",
    snippets_access_level: "enabled",
    pages_access_level: "enabled",
    operations_access_level: "enabled",
    analytics_access_level: "enabled",
    container_registry_access_level: "enabled",
    emails_disabled: null,
    shared_runners_enabled: true,
    lfs_enabled: true,
    creator_id: 123,
    import_status: "none",
    open_issues_count: 0,
    ci_default_git_depth: 50,
    ci_forward_deployment_enabled: true,
    ci_job_token_scope_enabled: false,
    public_jobs: true,
    build_timeout: 3600,
    auto_cancel_pending_pipelines: "enabled",
    build_coverage_regex: null,
    ci_config_path: null,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: false,
    allow_merge_on_skipped_pipeline: null,
    restrict_user_defined_variables: false,
    request_access_enabled: true,
    only_allow_merge_if_all_discussions_are_resolved: false,
    remove_source_branch_after_merge: true,
    printing_merge_request_link_enabled: true,
    merge_method: "merge",
    squash_option: "default_off",
    suggestion_commit_message: null,
    auto_devops_enabled: false,
    auto_devops_deploy_strategy: "continuous",
    autoclose_referenced_issues: true,
    keep_latest_artifact: true,
    permissions: { project_access: null, group_access: null },
  },
  {
    id: 71,
    description: "",
    name: "gerpgo-db",
    name_with_namespace: "release / gerpgo-db",
    path: "gerpgo-db",
    path_with_namespace: "release/gerpgo-db",
    created_at: "2021-07-01T11:07:48.415Z",
    default_branch: "master",
    tag_list: [],
    topics: [],
    ssh_url_to_repo: "git@gitlab.gerpgo.com:release/gerpgo-db.git",
    http_url_to_repo: "http://gitlab.gerpgo.com/release/gerpgo-db.git",
    web_url: "http://gitlab.gerpgo.com/release/gerpgo-db",
    readme_url: null,
    avatar_url: null,
    forks_count: 0,
    star_count: 0,
    last_activity_at: "2022-06-28T08:22:58.550Z",
    namespace: {
      id: 137,
      name: "release",
      path: "release",
      kind: "group",
      full_path: "release",
      parent_id: null,
      avatar_url: null,
      web_url: "http://gitlab.gerpgo.com/groups/release",
    },
    _links: {
      self: "http://gitlab.gerpgo.com/api/v4/projects/71",
      issues: "http://gitlab.gerpgo.com/api/v4/projects/71/issues",
      merge_requests:
        "http://gitlab.gerpgo.com/api/v4/projects/71/merge_requests",
      repo_branches:
        "http://gitlab.gerpgo.com/api/v4/projects/71/repository/branches",
      labels: "http://gitlab.gerpgo.com/api/v4/projects/71/labels",
      events: "http://gitlab.gerpgo.com/api/v4/projects/71/events",
      members: "http://gitlab.gerpgo.com/api/v4/projects/71/members",
    },
    packages_enabled: true,
    empty_repo: false,
    archived: false,
    visibility: "internal",
    resolve_outdated_diff_discussions: false,
    container_expiration_policy: {
      cadence: "1d",
      enabled: false,
      keep_n: 10,
      older_than: "90d",
      name_regex: null,
      name_regex_keep: null,
      next_run_at: "2021-12-28T21:50:03.096Z",
    },
    issues_enabled: true,
    merge_requests_enabled: true,
    wiki_enabled: true,
    jobs_enabled: true,
    snippets_enabled: true,
    container_registry_enabled: true,
    service_desk_enabled: false,
    service_desk_address: null,
    can_create_merge_request_in: true,
    issues_access_level: "enabled",
    repository_access_level: "enabled",
    merge_requests_access_level: "enabled",
    forking_access_level: "enabled",
    wiki_access_level: "enabled",
    builds_access_level: "enabled",
    snippets_access_level: "enabled",
    pages_access_level: "private",
    operations_access_level: "enabled",
    analytics_access_level: "enabled",
    container_registry_access_level: "enabled",
    emails_disabled: null,
    shared_runners_enabled: true,
    lfs_enabled: true,
    creator_id: 109,
    import_status: "none",
    open_issues_count: 0,
    ci_default_git_depth: 50,
    ci_forward_deployment_enabled: true,
    ci_job_token_scope_enabled: false,
    public_jobs: true,
    build_timeout: 3600,
    auto_cancel_pending_pipelines: "enabled",
    build_coverage_regex: null,
    ci_config_path: null,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: false,
    allow_merge_on_skipped_pipeline: null,
    restrict_user_defined_variables: false,
    request_access_enabled: true,
    only_allow_merge_if_all_discussions_are_resolved: false,
    remove_source_branch_after_merge: true,
    printing_merge_request_link_enabled: true,
    merge_method: "merge",
    squash_option: "default_off",
    suggestion_commit_message: null,
    auto_devops_enabled: true,
    auto_devops_deploy_strategy: "continuous",
    autoclose_referenced_issues: true,
    keep_latest_artifact: true,
    permissions: { project_access: null, group_access: null },
  },
  {
    id: 53,
    description: "gj component ui based on vue.js 2.x",
    name: "gj-component-ui",
    name_with_namespace: "易昶鸿 / gj-component-ui",
    path: "gj-component-ui",
    path_with_namespace: "lilqte/gj-component-ui",
    created_at: "2021-04-17T07:11:48.672Z",
    default_branch: "main",
    tag_list: [],
    topics: [],
    ssh_url_to_repo: "git@gitlab.gerpgo.com:lilqte/gj-component-ui.git",
    http_url_to_repo: "http://gitlab.gerpgo.com/lilqte/gj-component-ui.git",
    web_url: "http://gitlab.gerpgo.com/lilqte/gj-component-ui",
    readme_url: null,
    avatar_url: null,
    forks_count: 0,
    star_count: 0,
    last_activity_at: "2021-04-17T07:11:48.672Z",
    namespace: {
      id: 41,
      name: "易昶鸿",
      path: "lilqte",
      kind: "user",
      full_path: "lilqte",
      parent_id: null,
      avatar_url:
        "https://www.gravatar.com/avatar/ce89f69206cf22be9f7f199fb7adf8d9?s=80&d=identicon",
      web_url: "http://gitlab.gerpgo.com/lilqte",
    },
    _links: {
      self: "http://gitlab.gerpgo.com/api/v4/projects/53",
      issues: "http://gitlab.gerpgo.com/api/v4/projects/53/issues",
      merge_requests:
        "http://gitlab.gerpgo.com/api/v4/projects/53/merge_requests",
      repo_branches:
        "http://gitlab.gerpgo.com/api/v4/projects/53/repository/branches",
      labels: "http://gitlab.gerpgo.com/api/v4/projects/53/labels",
      events: "http://gitlab.gerpgo.com/api/v4/projects/53/events",
      members: "http://gitlab.gerpgo.com/api/v4/projects/53/members",
    },
    packages_enabled: true,
    empty_repo: true,
    archived: false,
    visibility: "public",
    owner: {
      id: 33,
      name: "易昶鸿",
      username: "lilqte",
      state: "blocked",
      avatar_url:
        "https://www.gravatar.com/avatar/ce89f69206cf22be9f7f199fb7adf8d9?s=80&d=identicon",
      web_url: "http://gitlab.gerpgo.com/lilqte",
    },
    resolve_outdated_diff_discussions: false,
    container_expiration_policy: {
      cadence: "1d",
      enabled: false,
      keep_n: 10,
      older_than: "90d",
      name_regex: null,
      name_regex_keep: null,
      next_run_at: "2021-12-28T11:50:37.873Z",
    },
    issues_enabled: true,
    merge_requests_enabled: true,
    wiki_enabled: true,
    jobs_enabled: true,
    snippets_enabled: true,
    container_registry_enabled: true,
    service_desk_enabled: false,
    service_desk_address: null,
    can_create_merge_request_in: true,
    issues_access_level: "enabled",
    repository_access_level: "enabled",
    merge_requests_access_level: "enabled",
    forking_access_level: "enabled",
    wiki_access_level: "enabled",
    builds_access_level: "enabled",
    snippets_access_level: "enabled",
    pages_access_level: "enabled",
    operations_access_level: "enabled",
    analytics_access_level: "enabled",
    container_registry_access_level: "enabled",
    emails_disabled: null,
    shared_runners_enabled: true,
    lfs_enabled: true,
    creator_id: 33,
    import_status: "none",
    open_issues_count: 0,
    ci_default_git_depth: 50,
    ci_forward_deployment_enabled: true,
    ci_job_token_scope_enabled: false,
    public_jobs: true,
    build_timeout: 3600,
    auto_cancel_pending_pipelines: "enabled",
    build_coverage_regex: null,
    ci_config_path: null,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: false,
    allow_merge_on_skipped_pipeline: null,
    restrict_user_defined_variables: false,
    request_access_enabled: true,
    only_allow_merge_if_all_discussions_are_resolved: false,
    remove_source_branch_after_merge: true,
    printing_merge_request_link_enabled: true,
    merge_method: "merge",
    squash_option: "default_off",
    suggestion_commit_message: null,
    auto_devops_enabled: true,
    auto_devops_deploy_strategy: "continuous",
    autoclose_referenced_issues: true,
    keep_latest_artifact: true,
    permissions: { project_access: null, group_access: null },
  },
  {
    id: 5,
    description: "X版前端代码（angular）",
    name: "erp-web-angular",
    name_with_namespace: "erp / erp-web-angular",
    path: "erp-web",
    path_with_namespace: "erp/erp-web",
    created_at: "2020-09-09T09:01:59.158Z",
    default_branch: "master",
    tag_list: [],
    topics: [],
    ssh_url_to_repo: "git@gitlab.gerpgo.com:erp/erp-web.git",
    http_url_to_repo: "http://gitlab.gerpgo.com/erp/erp-web.git",
    web_url: "http://gitlab.gerpgo.com/erp/erp-web",
    readme_url: "http://gitlab.gerpgo.com/erp/erp-web/-/blob/master/README.md",
    avatar_url: null,
    forks_count: 0,
    star_count: 0,
    last_activity_at: "2023-01-11T08:58:09.150Z",
    namespace: {
      id: 2,
      name: "erp",
      path: "erp",
      kind: "group",
      full_path: "erp",
      parent_id: null,
      avatar_url: null,
      web_url: "http://gitlab.gerpgo.com/groups/erp",
    },
    _links: {
      self: "http://gitlab.gerpgo.com/api/v4/projects/5",
      issues: "http://gitlab.gerpgo.com/api/v4/projects/5/issues",
      merge_requests:
        "http://gitlab.gerpgo.com/api/v4/projects/5/merge_requests",
      repo_branches:
        "http://gitlab.gerpgo.com/api/v4/projects/5/repository/branches",
      labels: "http://gitlab.gerpgo.com/api/v4/projects/5/labels",
      events: "http://gitlab.gerpgo.com/api/v4/projects/5/events",
      members: "http://gitlab.gerpgo.com/api/v4/projects/5/members",
    },
    packages_enabled: true,
    empty_repo: false,
    archived: false,
    visibility: "private",
    resolve_outdated_diff_discussions: false,
    container_expiration_policy: {
      cadence: "1d",
      enabled: false,
      keep_n: 10,
      older_than: "90d",
      name_regex: null,
      name_regex_keep: null,
      next_run_at: "2021-12-28T21:50:02.932Z",
    },
    issues_enabled: true,
    merge_requests_enabled: true,
    wiki_enabled: true,
    jobs_enabled: true,
    snippets_enabled: true,
    container_registry_enabled: true,
    service_desk_enabled: false,
    service_desk_address: null,
    can_create_merge_request_in: true,
    issues_access_level: "enabled",
    repository_access_level: "enabled",
    merge_requests_access_level: "enabled",
    forking_access_level: "enabled",
    wiki_access_level: "enabled",
    builds_access_level: "enabled",
    snippets_access_level: "enabled",
    pages_access_level: "private",
    operations_access_level: "enabled",
    analytics_access_level: "enabled",
    container_registry_access_level: "enabled",
    emails_disabled: null,
    shared_runners_enabled: true,
    lfs_enabled: true,
    creator_id: 2,
    import_status: "none",
    open_issues_count: 0,
    ci_default_git_depth: 50,
    ci_forward_deployment_enabled: true,
    ci_job_token_scope_enabled: false,
    public_jobs: true,
    build_timeout: 3600,
    auto_cancel_pending_pipelines: "enabled",
    build_coverage_regex: null,
    ci_config_path: null,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: false,
    allow_merge_on_skipped_pipeline: null,
    restrict_user_defined_variables: false,
    request_access_enabled: true,
    only_allow_merge_if_all_discussions_are_resolved: false,
    remove_source_branch_after_merge: true,
    printing_merge_request_link_enabled: true,
    merge_method: "merge",
    squash_option: "default_off",
    suggestion_commit_message: null,
    auto_devops_enabled: false,
    auto_devops_deploy_strategy: "continuous",
    autoclose_referenced_issues: true,
    keep_latest_artifact: true,
    permissions: { project_access: [Object], group_access: null },
  },
];
